"""
Integration Manager — dock an ENTIRE external project into Pragon, not just a
single .py file (that's what plugins/ + plugin_loader.py already do).

Where a plugin is one function Pragon calls in-process, an Integration is a
whole external project (any language, any framework) that:
  1. gets extracted from a user-uploaded .zip into its own folder,
  2. gets its OWN virtualenv (Python) or node_modules (Node) — fully isolated
     from Pragon's own dependencies and from every other docked integration,
  3. runs as a separate OS subprocess, so a crash or infinite loop in someone
     else's code can never take Pragon down with it,
  4. is controlled and queried the same way regardless of what's underneath:
     start / stop / status / logs, plus (for HTTP-serving integrations) named
     "commands" that become real AI-callable tools, and a raw request escape
     hatch for anything not explicitly declared.

DIRECTORY LAYOUT (per docked integration, "slug" = sanitized folder name):
    integrations/<slug>/
        src/                 <- the zip contents (flattened if the zip had a
                                 single top-level wrapper folder)
        venv/                <- python -m venv, Python projects only
        integration.json     <- the RESOLVED manifest actually in use (either
                                 copied from the zip or generated by detection)
        state.json           <- port, pid, status, last error — survives restarts
        run.log              <- captured stdout/stderr of the running process

MANIFEST (optional — a top-level integration.json or pragon.json inside the
zip). Anything omitted is filled in by detection:
{
  "name": "my_service",                 snake_case, unique
  "description": "What this does, for the AI to decide when to use it.",
  "runtime": "python" | "node" | "script",
  "install": "pip install -r requirements.txt",   # optional, auto-guessed
  "start": "python app.py --port {port}",         # {port} substituted in
  "serves_http": true,                            # false => one-shot CLI tool
  "health_path": "/health",                       # optional extra readiness check
  "commands": [
    {"name": "get_status", "description": "...", "method": "GET",  "path": "/status"},
    {"name": "run_task",   "description": "...", "method": "POST", "path": "/run",
     "parameters": {"type": "OBJECT", "properties": {"topic": {"type": "STRING"}}}}
  ]
}

With NO manifest at all, Pragon still docks the project: it guesses the
runtime and start command from requirements.txt / package.json / common
entrypoint filenames, installs dependencies, and can run/stop/log it and hit
it with the generic raw-request tool — it just won't have named commands
until a manifest (or an update to one) declares them.

Never raises out into caller code: every public method returns either a
plain value/tuple or leaves .error set on the record, mirroring the safety
contract plugin_loader.py already established for single-file plugins.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import signal
import socket
import subprocess
import sys
import threading
import time
import traceback
import zipfile
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Callable, Optional

_NAME_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_\-]{0,63}$")
_MANIFEST_NAMES = ("integration.json", "pragon.json")


def _slugify(filename: str) -> str:
    stem = Path(filename).stem
    slug = re.sub(r"[^a-zA-Z0-9_\-]", "_", stem).strip("_") or "integration"
    return slug[:64]


def _find_free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _port_open(port: int, host: str = "127.0.0.1") -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.5)
        try:
            return s.connect_ex((host, port)) == 0
        except Exception:
            return False


@dataclass
class IntegrationRecord:
    slug: str
    name: str = ""
    description: str = ""
    runtime: str = "unknown"          # python | node | script | unknown
    serves_http: bool = False
    commands: list = field(default_factory=list)
    status: str = "stopped"           # stopped | installing | running | error
    port: Optional[int] = None
    pid: Optional[int] = None
    error: str = ""
    path: str = ""                    # integrations/<slug>


class IntegrationManager:
    def __init__(self, integrations_dir: Path, logger: Callable[[str], None] = print):
        self.dir = Path(integrations_dir)
        self.dir.mkdir(parents=True, exist_ok=True)
        self._logger = logger
        self._records: dict[str, IntegrationRecord] = {}
        self._procs: dict[str, subprocess.Popen] = {}
        self._lock = threading.RLock()
        self._load_existing()

    # ------------------------------------------------------------------ #
    # discovery / persistence
    # ------------------------------------------------------------------ #
    def _load_existing(self):
        """Rebuild records for integrations already docked from a previous run.
        Everything comes back as 'stopped' — Pragon never auto-restarts a
        subprocess from a prior process lifetime."""
        for sub in sorted(self.dir.glob("*")):
            if not sub.is_dir():
                continue
            state_file = sub / "state.json"
            manifest_file = sub / "integration.json"
            if not manifest_file.exists():
                continue
            try:
                manifest = json.loads(manifest_file.read_text(encoding="utf-8"))
            except Exception:
                manifest = {}
            rec = IntegrationRecord(
                slug=sub.name,
                name=manifest.get("name", sub.name),
                description=manifest.get("description", ""),
                runtime=manifest.get("runtime", "unknown"),
                serves_http=bool(manifest.get("serves_http")),
                commands=manifest.get("commands", []),
                status="stopped",
                path=str(sub),
            )
            if state_file.exists():
                try:
                    st = json.loads(state_file.read_text(encoding="utf-8"))
                    if st.get("status") == "error":
                        rec.status, rec.error = "error", st.get("error", "")
                except Exception:
                    pass
            self._records[rec.slug] = rec
            self._logger(f"Integration restored: {rec.name} ({rec.slug}) — stopped, click Start to resume.")

    def _save_state(self, rec: IntegrationRecord):
        state_file = Path(rec.path) / "state.json"
        try:
            state_file.write_text(json.dumps({
                "status": rec.status, "port": rec.port, "pid": rec.pid, "error": rec.error,
            }, indent=2), encoding="utf-8")
        except Exception:
            pass

    def list_for_ui(self) -> list[dict]:
        with self._lock:
            return [asdict(r) for r in self._records.values()]

    def has(self, slug: str) -> bool:
        return slug in self._records

    # ------------------------------------------------------------------ #
    # ingest
    # ------------------------------------------------------------------ #
    def install_zip(self, filename: str, data: bytes) -> tuple[bool, str]:
        """Extract an uploaded zip, resolve its manifest, and kick off
        dependency installation in the background. Returns (ok, message)."""
        if not filename.lower().endswith(".zip"):
            return False, "Only .zip files can be docked as integrations."
        if len(data) > 200_000_000:
            return False, "Zip is too large (200MB limit)."

        slug = _slugify(filename)
        base = slug
        n = 1
        while (self.dir / slug).exists():
            n += 1
            slug = f"{base}_{n}"

        target = self.dir / slug
        src = target / "src"
        try:
            src.mkdir(parents=True, exist_ok=True)
            tmp_zip = target / "_upload.zip"
            tmp_zip.write_bytes(data)
            with zipfile.ZipFile(tmp_zip) as zf:
                _safe_extract(zf, src)
            tmp_zip.unlink(missing_ok=True)
            _flatten_single_wrapper_dir(src)
        except Exception as e:
            shutil.rmtree(target, ignore_errors=True)
            return False, f"Failed to unpack zip: {e}"

        rec = IntegrationRecord(slug=slug, path=str(target), status="installing")
        with self._lock:
            self._records[slug] = rec

        try:
            self._resolve_manifest(rec, src)
        except Exception as e:
            rec.status, rec.error = "error", f"Failed to read project: {e}"
            self._save_state(rec)
            return True, f"Docked '{slug}' but couldn't analyze it: {e}"

        threading.Thread(target=self._install_background, args=(rec,), daemon=True).start()
        return True, f"'{rec.name}' docked — installing dependencies…"

    def _resolve_manifest(self, rec: IntegrationRecord, src: Path):
        manifest = None
        for mname in _MANIFEST_NAMES:
            mfile = src / mname
            if mfile.exists():
                try:
                    manifest = json.loads(mfile.read_text(encoding="utf-8"))
                except Exception as e:
                    raise ValueError(f"Malformed {mname}: {e}")
                break

        detected = _detect_project(src)
        if manifest:
            rec.name = manifest.get("name") or rec.slug
            rec.description = manifest.get("description", "") or detected["description"]
            rec.runtime = manifest.get("runtime") or detected["runtime"]
            rec.serves_http = bool(manifest.get("serves_http", detected["serves_http"]))
            rec.commands = manifest.get("commands", [])
            install_cmd = manifest.get("install") or detected["install"]
            start_cmd = manifest.get("start") or detected["start"]
            health_path = manifest.get("health_path", "")
        else:
            rec.name = rec.slug
            rec.description = detected["description"]
            rec.runtime = detected["runtime"]
            rec.serves_http = detected["serves_http"]
            rec.commands = []
            install_cmd = detected["install"]
            start_cmd = detected["start"]
            health_path = ""

        if not _NAME_RE.match(rec.name):
            rec.name = rec.slug

        resolved = {
            "name": rec.name, "description": rec.description, "runtime": rec.runtime,
            "serves_http": rec.serves_http, "commands": rec.commands,
            "install": install_cmd, "start": start_cmd, "health_path": health_path,
        }
        (Path(rec.path) / "integration.json").write_text(json.dumps(resolved, indent=2), encoding="utf-8")
        rec._resolved = resolved  # stashed for _install_background/start, not persisted on the dataclass

    # ------------------------------------------------------------------ #
    # dependency install (background thread — can take a while)
    # ------------------------------------------------------------------ #
    def _install_background(self, rec: IntegrationRecord):
        src = Path(rec.path) / "src"
        venv_dir = Path(rec.path) / "venv"
        resolved = getattr(rec, "_resolved", {})
        install_cmd = resolved.get("install", "")
        try:
            if rec.runtime == "python":
                subprocess.run([sys.executable, "-m", "venv", str(venv_dir)], check=True,
                                capture_output=True, timeout=180)
                pip = str(venv_dir / ("Scripts/pip.exe" if os.name == "nt" else "bin/pip"))
                if install_cmd:
                    cmd = install_cmd.replace("pip ", f'"{pip}" ', 1) if install_cmd.startswith("pip ") else install_cmd
                    subprocess.run(cmd, shell=True, cwd=src, capture_output=True, timeout=900)
            elif rec.runtime == "node":
                if install_cmd:
                    subprocess.run(install_cmd, shell=True, cwd=src, capture_output=True, timeout=900)
            # runtime == "script"/"unknown": nothing to install beyond what's in the zip
            rec.status = "stopped"
            rec.error = ""
        except subprocess.CalledProcessError as e:
            rec.status, rec.error = "error", f"Install failed: {e.stderr.decode(errors='ignore')[:500] if e.stderr else e}"
        except Exception as e:
            rec.status, rec.error = "error", f"Install failed: {e}"
        self._save_state(rec)
        self._logger(f"Integration '{rec.name}' install finished — status: {rec.status}")

    # ------------------------------------------------------------------ #
    # process lifecycle
    # ------------------------------------------------------------------ #
    def start(self, slug: str) -> str:
        rec = self._records.get(slug)
        if not rec:
            return f"'{slug}' not found."
        if rec.status == "installing":
            return f"'{rec.name}' is still installing dependencies — try again shortly."
        if rec.status == "running":
            return f"'{rec.name}' is already running."

        manifest_file = Path(rec.path) / "integration.json"
        try:
            resolved = json.loads(manifest_file.read_text(encoding="utf-8"))
        except Exception as e:
            return f"Couldn't read manifest for '{rec.name}': {e}"

        start_cmd = resolved.get("start", "")
        if not start_cmd:
            rec.status, rec.error = "error", "No start command known — couldn't detect how to run this project."
            self._save_state(rec)
            return rec.error

        src = Path(rec.path) / "src"
        env = os.environ.copy()
        port = None
        if rec.serves_http:
            port = _find_free_port()
            start_cmd = start_cmd.replace("{port}", str(port))
            env["PORT"] = str(port)

        if rec.runtime == "python":
            venv_py = Path(rec.path) / "venv" / ("Scripts/python.exe" if os.name == "nt" else "bin/python")
            if venv_py.exists() and start_cmd.split(" ", 1)[0] in ("python", "python3"):
                start_cmd = str(venv_py) + start_cmd[start_cmd.find(" "):]

        try:
            log_file = open(Path(rec.path) / "run.log", "ab", buffering=0)
            proc = subprocess.Popen(
                start_cmd, shell=True, cwd=src, env=env,
                stdout=log_file, stderr=subprocess.STDOUT,
                preexec_fn=None if os.name == "nt" else os.setsid,
            )
        except Exception as e:
            rec.status, rec.error = "error", f"Failed to launch: {e}"
            self._save_state(rec)
            return rec.error

        self._procs[slug] = proc
        rec.pid, rec.port, rec.error = proc.pid, port, ""

        if rec.serves_http:
            def _wait_ready():
                deadline = time.monotonic() + 20
                while time.monotonic() < deadline:
                    if proc.poll() is not None:
                        rec.status = "error"
                        rec.error = f"Process exited immediately (code {proc.returncode}) — check logs."
                        self._save_state(rec)
                        return
                    if _port_open(port):
                        rec.status = "running"
                        self._save_state(rec)
                        return
                    time.sleep(0.4)
                rec.status, rec.error = "error", "Timed out waiting for the integration to open its port."
                self._save_state(rec)
            threading.Thread(target=_wait_ready, daemon=True).start()
            rec.status = "installing"  # transient "starting…" state reusing the same UI badge
            return f"Starting '{rec.name}'…"
        else:
            rec.status = "running"
            self._save_state(rec)
            return f"'{rec.name}' started."

    def stop(self, slug: str) -> str:
        rec = self._records.get(slug)
        if not rec:
            return f"'{slug}' not found."
        proc = self._procs.get(slug)
        if not proc or proc.poll() is not None:
            rec.status = "stopped"
            self._save_state(rec)
            return f"'{rec.name}' is not running."
        try:
            if os.name == "nt":
                proc.terminate()
            else:
                os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
            proc.wait(timeout=8)
        except Exception:
            try:
                if os.name == "nt":
                    proc.kill()
                else:
                    os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
            except Exception:
                pass
        self._procs.pop(slug, None)
        rec.status, rec.pid, rec.error = "stopped", None, ""
        self._save_state(rec)
        return f"'{rec.name}' stopped."

    def delete(self, slug: str) -> str:
        rec = self._records.get(slug)
        if not rec:
            return f"'{slug}' not found."
        self.stop(slug)
        shutil.rmtree(rec.path, ignore_errors=True)
        with self._lock:
            self._records.pop(slug, None)
        return f"'{rec.name}' undocked."

    def logs(self, slug: str, tail_lines: int = 200) -> str:
        rec = self._records.get(slug)
        if not rec:
            return f"'{slug}' not found."
        log_file = Path(rec.path) / "run.log"
        if not log_file.exists():
            return "(no logs yet)"
        try:
            data = log_file.read_bytes()[-200_000:]  # cap how much we ever read
            lines = data.decode(errors="ignore").splitlines()
            return "\n".join(lines[-tail_lines:]) or "(empty)"
        except Exception as e:
            return f"(couldn't read logs: {e})"

    # ------------------------------------------------------------------ #
    # data fetch / control — the uniform interface regardless of runtime
    # ------------------------------------------------------------------ #
    def call(self, slug: str, method: str = "GET", path: str = "/",
              params: Optional[dict] = None, json_body: Optional[dict] = None) -> str:
        rec = self._records.get(slug)
        if not rec:
            return f"'{slug}' not found."
        if not rec.serves_http:
            return f"'{rec.name}' doesn't expose an HTTP interface."
        if rec.status != "running" or not rec.port:
            return f"'{rec.name}' isn't running — start it first."
        try:
            import requests
            url = f"http://127.0.0.1:{rec.port}{path if path.startswith('/') else '/' + path}"
            resp = requests.request(method.upper(), url, params=params, json=json_body, timeout=20)
            text = resp.text
            return text if len(text) <= 4000 else text[:4000] + " …[truncated]"
        except Exception as e:
            return f"Request to '{rec.name}' failed: {e}"

    # ------------------------------------------------------------------ #
    # AI tool bridge — mirrors PluginRegistry.get_tool_declarations()/run()
    # ------------------------------------------------------------------ #
    def get_tool_declarations(self) -> list[dict]:
        decls = []
        for rec in self._records.values():
            if rec.status not in ("running",) or not rec.serves_http:
                continue
            for cmd in rec.commands:
                decls.append({
                    "name": f"integration_{rec.slug}_{cmd['name']}",
                    "description": f"[{rec.name} integration] {cmd.get('description', '')}",
                    "parameters": cmd.get("parameters", {"type": "OBJECT", "properties": {}}),
                })
        return decls

    def run_tool(self, tool_name: str, parameters: dict) -> Optional[str]:
        """Returns None if tool_name doesn't belong to any integration (so the
        caller can fall through to its next handler), else the result string."""
        if not tool_name.startswith("integration_"):
            return None
        for rec in self._records.values():
            prefix = f"integration_{rec.slug}_"
            if tool_name.startswith(prefix):
                cmd_name = tool_name[len(prefix):]
                cmd = next((c for c in rec.commands if c["name"] == cmd_name), None)
                if not cmd:
                    return f"'{cmd_name}' is not a known command of '{rec.name}'."
                method = cmd.get("method", "GET").upper()
                path = cmd.get("path", "/")
                if method == "GET":
                    return self.call(rec.slug, method, path, params=parameters)
                return self.call(rec.slug, method, path, json_body=parameters)
        return None


# ---------------------------------------------------------------------- #
# zip / project helpers
# ---------------------------------------------------------------------- #

def _safe_extract(zf: zipfile.ZipFile, dest: Path):
    dest = dest.resolve()
    for member in zf.infolist():
        member_path = (dest / member.filename).resolve()
        if not str(member_path).startswith(str(dest)):
            raise ValueError(f"Unsafe path in zip: {member.filename}")
    zf.extractall(dest)


def _flatten_single_wrapper_dir(src: Path):
    """Many zips wrap everything in one top-level folder (GitHub-style
    'myproject-main/'). If that's the only thing in src, hoist its contents
    up a level so requirements.txt/package.json etc. are found at src/."""
    entries = list(src.iterdir())
    if len(entries) == 1 and entries[0].is_dir():
        wrapper = entries[0]
        for item in wrapper.iterdir():
            shutil.move(str(item), str(src / item.name))
        wrapper.rmdir()


def _detect_project(src: Path) -> dict:
    """Best-effort guess of runtime/install/start/serves_http when no manifest
    is present. Deliberately conservative — an integration that lands as
    runtime 'unknown' with no start command just can't be started until the
    user supplies (or edits) an integration.json; it's still browsable/deletable."""
    has = lambda name: (src / name).exists()
    files = {p.name for p in src.glob("*")}

    if has("package.json"):
        try:
            pkg = json.loads((src / "package.json").read_text(encoding="utf-8"))
        except Exception:
            pkg = {}
        start_script = (pkg.get("scripts") or {}).get("start")
        entry = pkg.get("main") or "index.js"
        start = "npm start" if start_script else f"node {entry}"
        serves_http = _greps_for_server(src, extensions=(".js",))
        return {
            "runtime": "node", "install": "npm install", "start": start,
            "serves_http": serves_http,
            "description": pkg.get("description") or f"Node.js project ({pkg.get('name', src.name)}).",
        }

    if has("requirements.txt") or has("pyproject.toml") or has("setup.py") or any(f.endswith(".py") for f in files):
        entry = None
        for candidate in ("app.py", "main.py", "server.py", "run.py"):
            if has(candidate):
                entry = candidate
                break
        if not entry:
            py_files = list(src.glob("*.py"))
            entry = py_files[0].name if py_files else None
        install = "pip install -r requirements.txt" if has("requirements.txt") else ""
        start = f"python {entry}" if entry else ""
        serves_http = _greps_for_server(src, extensions=(".py",))
        return {
            "runtime": "python", "install": install, "start": start,
            "serves_http": serves_http,
            "description": f"Python project (entry: {entry or 'unknown'}).",
        }

    return {
        "runtime": "unknown", "install": "", "start": "",
        "serves_http": False,
        "description": "Unrecognized project layout — couldn't auto-detect how to run this. "
                        "Add an integration.json manifest to make it runnable.",
    }


_SERVER_HINTS = (
    "app.run(", "Flask(", "FastAPI(", "uvicorn.run(", "runserver",
    "app.listen(", "createServer(", "express()", ".listen(",
)


def _greps_for_server(src: Path, extensions: tuple[str, ...], max_files: int = 40) -> bool:
    """Cheap heuristic: does this project look like it starts an HTTP server?
    Only used to decide serves_http when no manifest says so explicitly."""
    checked = 0
    for path in src.rglob("*"):
        if path.suffix not in extensions or "node_modules" in path.parts or "venv" in path.parts:
            continue
        checked += 1
        if checked > max_files:
            break
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        if any(hint in text for hint in _SERVER_HINTS):
            return True
    return False
