"""
agent_builder.py - generates standalone, deployable autonomous agents.
"""

import json
import re
import uuid
from pathlib import Path
from datetime import datetime

# NOTE: TOOL_REGISTRY is intentionally NOT imported at module level here.
# registry.py imports this module (agent_builder.py) to register the
# "agent_builder" tool, so a top-level `from .registry import TOOL_REGISTRY`
# in this file creates a circular import (registry -> agent_builder ->
# registry, the last of which isn't finished executing yet and doesn't have
# TOOL_REGISTRY defined). Every function below that needs it imports it
# lazily instead, by which point registry.py has finished loading.

# Every generated agent is ALSO saved here, regardless of output_path/Desktop
# — that save happens on the machine running the server, which the person
# using the canvas in a browser may not have filesystem access to (a remote
# server, a container, a different machine on the network). This directory
# is what /api/export-agent/<filename> in server.py serves from, so the
# generated .py can be pulled down as a real browser download no matter
# where the server is running.
EXPORTS_DIR = Path(__file__).resolve().parent.parent / "exports"


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")
    return slug[:40] or "agent"


def _escape_py_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r")


def _generate_agent_code(goal: str, allowed_tools: list, model: str, max_iterations: int) -> str:
    from .registry import TOOL_REGISTRY  # lazy import — see note at top of file
    tool_ids = [t for t in allowed_tools if t in TOOL_REGISTRY and t != "gemini_agent"]
    if not tool_ids:
        tool_ids = [t for t in TOOL_REGISTRY.keys() if t != "gemini_agent"]

    allowed_list = json.dumps(tool_ids)
    safe_goal = _escape_py_string(goal)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    code = '''#!/usr/bin/env python3
"""
Autonomous Agent - Generated by FORGE Agent Builder
Generated: __TIMESTAMP__
====================================================
Goal: __GOAL__
Model: __MODEL__
Max iterations: __MAX_ITERATIONS__
Allowed tools: __ALLOWED_TOOLS__

Run this agent standalone:
    python agent_generated.py

Model routing:
  - Default ("auto") uses a free local model via Ollama
    (https://ollama.com) first — no API key, no quota — and
    automatically falls back to Gemini (config/api_keys.json) as backup
    power if Ollama isn't installed/running.
  - "ollama:<model>" (e.g. "ollama:llama3.2") forces the local model only.
  - "gemini-2.5-flash" forces the cloud model only.
  Install Ollama, run `ollama serve`, and `ollama pull qwen2.5-coder:3b`
  (or any model you like) to use the free local engine.
"""

import json
import re
import sys
from pathlib import Path


def _find_project_root():
    start = Path(__file__).resolve().parent
    for path in [start] + list(start.parents):
        if (path / "tools" / "registry.py").exists():
            return path
    return Path.cwd()


PROJECT_ROOT = _find_project_root()
sys.path.insert(0, str(PROJECT_ROOT))

from tools.registry import run_tool, TOOL_REGISTRY
from tools.llm_client import get_model, LLMError

DEFAULT_MODEL = "__MODEL__"
DEFAULT_MAX_ITERATIONS = __MAX_ITERATIONS__
GOAL = "__SAFE_GOAL__"
ALLOWED_TOOLS = __ALLOWED_LIST__

FINAL_RE = re.compile(r"Final Answer:\\s*(.*)", re.DOTALL)
ACTION_RE = re.compile(r"Action:\\s*([a-zA-Z_]+)\\s*\\nAction Input:\\s*(\\{.*\\})", re.DOTALL)
THOUGHT_RE = re.compile(r"Thought:\\s*(.*?)(?=\\nAction:|\\nFinal Answer:|\\Z)", re.DOTALL)


def _tool_descriptions():
    lines = []
    for tool_id in ALLOWED_TOOLS:
        meta = TOOL_REGISTRY.get(tool_id)
        if not meta:
            continue
        field_list = ", ".join(f'"{f["name"]}"' for f in meta.get("fields", []))
        lines.append(f"- {tool_id}: {meta['description']}  Parameters: {field_list}")
    return "\n".join(lines)


def _build_prompt(scratchpad: str) -> str:
    return f"""You are an autonomous agent working step by step toward a goal.

Available tools:
{_tool_descriptions()}

Respond with EXACTLY one of these two formats, nothing else:

Thought: <your reasoning about what to do next>
Action: <one tool id from the list above, exactly as written>
Action Input: <a single JSON object with that tool's parameters>

OR, once you have enough information to fully answer the goal:

Thought: <your reasoning>
Final Answer: <the complete answer to the goal>

Goal: {GOAL}
{scratchpad}"""


def _extract_json_object(text: str):
    if not text:
        return None
    idx = text.find("{")
    if idx == -1:
        return None
    decoder = json.JSONDecoder()
    try:
        obj, _ = decoder.raw_decode(text[idx:])
        return obj
    except Exception:
        return None


def _parse_step(text: str) -> dict:
    thought_match = THOUGHT_RE.search(text)
    thought = thought_match.group(1).strip() if thought_match else ""

    final_idx = text.find("Final Answer:")
    action_idx = text.find("Action:")
    if final_idx != -1 and (action_idx == -1 or final_idx < action_idx):
        final_match = FINAL_RE.search(text)
        if final_match:
            return {"thought": thought, "final_answer": final_match.group(1).strip()}

    action_match = ACTION_RE.search(text)
    if action_match:
        return {
            "thought": thought,
            "action": action_match.group(1).strip(),
            "action_input": _extract_json_object(action_match.group(2)),
            "raw_input": action_match.group(2).strip(),
        }

    return {"thought": thought or text.strip(), "unparsed": text.strip()}


def run_agent():
    model = get_model(DEFAULT_MODEL)
    scratchpad = ""
    seen_calls = set()
    transcript = []

    print("=" * 60)
    print("AUTONOMOUS AGENT")
    print("=" * 60)
    print(f"Goal: {GOAL}")
    print(f"Tools: {', '.join(ALLOWED_TOOLS)}")
    print(f"Model: {DEFAULT_MODEL}")
    print(f"Max steps: {DEFAULT_MAX_ITERATIONS}")
    print("=" * 60)

    for step_num in range(1, DEFAULT_MAX_ITERATIONS + 1):
        prompt = _build_prompt(scratchpad)

        try:
            resp = model.generate_content(prompt)
            text = (resp.text or "").strip()
        except Exception as e:
            print(f"\nModel error: {e}")
            transcript.append({"step": step_num, "error": str(e)})
            break

        print(f"\n--- Step {step_num} ---")

        parsed = _parse_step(text)

        if "final_answer" in parsed:
            print(f"Thought: {parsed['thought']}")
            print(f"Final Answer: {parsed['final_answer']}")
            transcript.append({
                "step": step_num,
                "thought": parsed["thought"],
                "final_answer": parsed["final_answer"],
            })
            _save_transcript(transcript)
            return parsed["final_answer"]

        action = parsed.get("action")
        if not action:
            print("Unparsed response - retrying...")
            scratchpad += (
                f"\n{text}\n"
                f"Observation: Your last response didn't follow the required format. Try again.\n"
            )
            transcript.append({"step": step_num, "raw": text, "error": "unparsed"})
            continue

        if action not in ALLOWED_TOOLS:
            obs = f"Unknown tool '{action}'. Available: {', '.join(ALLOWED_TOOLS)}"
            print(f"{obs}")
            scratchpad += f"\nThought: {parsed['thought']}\nAction: {action}\nObservation: {obs}\n"
            transcript.append({"step": step_num, "thought": parsed["thought"], "action": action, "observation": obs})
            continue

        action_input = parsed.get("action_input") or {}
        call_sig = (action, json.dumps(action_input, sort_keys=True))

        if call_sig in seen_calls:
            obs = "You already made this exact call. Use a different action or give your Final Answer."
            print(f"{obs}")
        else:
            seen_calls.add(call_sig)
            print(f"{action}({json.dumps(action_input)})")
            try:
                obs = run_tool(action, dict(action_input))
            except Exception as e:
                obs = f"Tool error: {e}"
            print(f"{obs[:500]}{'...' if len(obs) > 500 else ''}")

        scratchpad += (
            f"\nThought: {parsed['thought']}\n"
            f"Action: {action}\n"
            f"Action Input: {json.dumps(action_input)}\n"
            f"Observation: {obs[:1500]}\n"
        )
        transcript.append({
            "step": step_num,
            "thought": parsed["thought"],
            "action": action,
            "action_input": action_input,
            "observation": obs[:1500],
        })

    print(f"\nStopped after {DEFAULT_MAX_ITERATIONS} steps without a Final Answer.")
    _save_transcript(transcript)
    return None


def _save_transcript(transcript: list):
    path = PROJECT_ROOT / "workflows" / "agent_transcript.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(transcript, indent=2), encoding="utf-8")
    print(f"\nTranscript saved: {path}")


if __name__ == "__main__":
    run_agent()
'''

    code = code.replace("__TIMESTAMP__", timestamp)
    code = code.replace("__GOAL__", goal)
    code = code.replace("__MODEL__", model)
    code = code.replace("__MAX_ITERATIONS__", str(max_iterations))
    code = code.replace("__ALLOWED_TOOLS__", ", ".join(tool_ids))
    code = code.replace("__SAFE_GOAL__", safe_goal)
    code = code.replace("__ALLOWED_LIST__", allowed_list)

    return code


def build_agent(parameters: dict = None, **kwargs) -> str:
    from .registry import TOOL_REGISTRY  # lazy import — see note at top of file
    params = parameters or {}
    goal = (params.get("goal") or params.get("description") or "No goal set").strip()
    model = params.get("model", "auto").strip()
    max_iter = int(params.get("max_iterations", 10))
    output_path = params.get("output_path", "").strip()

    real_tools = [t for t in TOOL_REGISTRY.keys() if t != "gemini_agent"]
    allowed = params.get("allowed_tools") or real_tools
    allowed = [t for t in allowed if t in real_tools] or real_tools

    code = _generate_agent_code(goal, allowed, model, max_iter)

    if output_path:
        save_path = Path(output_path)
        if not save_path.is_absolute():
            save_path = Path.home() / "Desktop" / save_path
    else:
        save_path = Path.home() / "Desktop" / "agent_generated.py"

    save_path.parent.mkdir(parents=True, exist_ok=True)
    save_path.write_text(code, encoding="utf-8")

    # Also drop a copy in exports/ under a unique name, so it can be pulled
    # down as a browser download via /api/export-agent/<filename> — see the
    # EXPORTS_DIR comment above for why this exists alongside save_path.
    EXPORTS_DIR.mkdir(parents=True, exist_ok=True)
    export_name = f"{_slugify(goal)}-{uuid.uuid4().hex[:8]}.py"
    export_path = EXPORTS_DIR / export_name
    export_path.write_text(code, encoding="utf-8")

    preview = code[:800] + ("\n..." if len(code) > 800 else "")
    parts = [
        "Standalone agent generated and saved to:\n  " + str(save_path) + "\n\n",
        "Goal: " + goal + "\n",
        "Tools: " + ", ".join(allowed) + "\n",
        "Model: " + model + "\n",
        "Max steps: " + str(max_iter) + "\n\n",
        "Code preview:\n" + "-"*40 + "\n" + preview + "\n" + "-"*40 + "\n\n",
        'Run it: python "' + str(save_path) + '"\n\n',
        "Export URL: /api/export-agent/" + export_name,
    ]
    return "".join(parts)
