// PRAGON WhatsUp — Node sidecar
//
// Talks whatsapp-web.js on one side, newline-delimited JSON on the other.
// The Python side (bridge.py) spawns this process, reads stdout for events,
// and writes stdin for outgoing sends. Kept intentionally dumb: no LLM
// calls happen here — every reply is generated by FRIDAY in Python and
// handed back down over stdin.
//
// Events emitted on stdout (one JSON object per line):
//   {"type":"qr","dataUri":"data:image/png;base64,..."}
//   {"type":"ready"}
//   {"type":"message","from":"91xxxxxxxxxx@c.us","text":"..."}
//   {"type":"disconnected","reason":"..."}
//   {"type":"error","message":"..."}
//
// Commands read from stdin (one JSON object per line):
//   {"type":"send","to":"91xxxxxxxxxx@c.us","text":"..."}

const { Client, LocalAuth } = require('whatsapp-web.js');
const qrcode = require('qrcode');
const readline = require('readline');

function emit(obj) {
  process.stdout.write(JSON.stringify(obj) + '\n');
}

const client = new Client({
  authStrategy: new LocalAuth({ clientId: 'pragon-whatsup' }),
  puppeteer: {
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  },
});

// Known whatsapp-web.js issue: after a successful scan on the phone, the
// 'ready' event can sometimes never fire (see wwebjs/whatsapp-web.js#5751).
// Rather than leaving the UI stuck on "waiting for scan" forever, surface a
// clear timeout error so the person knows to retry / clear the auth folder.
let readyTimeout = null;

client.on('qr', async (qr) => {
  try {
    const dataUri = await qrcode.toDataURL(qr);
    emit({ type: 'qr', dataUri });
  } catch (err) {
    emit({ type: 'error', message: `QR generation failed: ${err.message}` });
  }
});

client.on('authenticated', () => {
  emit({ type: 'authenticated' });
  clearTimeout(readyTimeout);
  readyTimeout = setTimeout(() => {
    emit({
      type: 'error',
      message: (
        'Scan succeeded but the connection never finished (known ' +
        'whatsapp-web.js issue). Try: stop Pragon, delete the ' +
        '.wwebjs_auth folder inside pragon_whatsapp/, restart, and scan a ' +
        'fresh QR code.'
      ),
    });
  }, 45000);
});

client.on('ready', () => {
  clearTimeout(readyTimeout);
  emit({ type: 'ready' });
});

client.on('disconnected', (reason) => {
  emit({ type: 'disconnected', reason: String(reason) });
});

client.on('message', async (message) => {
  try {
    const from = message.from;
    const text = message.body;

    if (from.endsWith('@g.us')) return; // skip group chats, 1:1 only
    if (!text || text.trim() === '') return;

    emit({ type: 'message', from, text });
  } catch (err) {
    emit({ type: 'error', message: `Message handling failed: ${err.message}` });
  }
});

// Read commands from Python over stdin
const rl = readline.createInterface({ input: process.stdin, terminal: false });
rl.on('line', async (line) => {
  if (!line.trim()) return;
  let cmd;
  try {
    cmd = JSON.parse(line);
  } catch {
    return; // ignore malformed lines
  }

  if (cmd.type === 'send' && cmd.to && typeof cmd.text === 'string') {
    try {
      await client.sendMessage(cmd.to, cmd.text);
    } catch (err) {
      emit({ type: 'error', message: `Send failed: ${err.message}` });
    }
  }
});

process.on('unhandledRejection', (err) => {
  emit({ type: 'error', message: `Unhandled: ${err && err.message ? err.message : err}` });
});

emit({ type: 'starting' });
client.initialize().catch((err) => {
  emit({ type: 'error', message: `initialize() failed: ${err && err.message ? err.message : err}` });
});
